updated twitter.py and ronaAnalysis-ncdc.py
Pandelytics/pandelytics pull request #11
Opened 2020-04-19 00:26 UTC by SLKhadeeja

fixes #10

2020-04-19 02:31 UTC, deven96 reviewed
Is the ncdc parser working now?

2020-04-19 02:31 UTC, deven96 commented on Scripts/Activate.ps1
> +}
You can exclude your entire scripts folder and all virtualenv related stuff by removing it from your git cache and adding it to your gitignore

2020-04-19 02:31 UTC, deven96 commented on pyvenv.cfg
> +version = 3.7.6
Also goes in gitignore

2020-04-19 05:02 UTC, SLKhadeeja commented
It's working now

Sorry.... I forgot about the virtual env.... I'll fix it

2020-04-19 12:04 UTC, MeNsaaH requested changes

2020-04-19 12:04 UTC, MeNsaaH commented on ronaAnalysis-ncdc.py
> +import requests
Could you please move this implementation to the ncdc file https://github.com/Pandelytics/pandelytics/blob/master/pandelytics/engines/ncdc.py

Use the class base approach

2020-04-22 08:43 UTC, MeNsaaH submitted a review, later dismissed

2020-04-22 08:44 UTC, MeNsaaH commented
@SLKhadeeja could you resolve the merge conflicts. On you branch execute
```git fetch origin master
	git merge origin/master
```
Resolve the conflicts that occur and push them

2020-04-23 15:30 UTC, MeNsaaH approved these changes

2020-04-23 15:30 UTC, merged